[package]
name = "termilog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
ratatui = "0.25.0"
# regex = "1.7.1"
self_cell = "1.0.3"
# tui = "0.19.0"
